name: renew

on:
  workflow_dispatch:
  schedule:
    - cron: '39 20 * * *'
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    strategy:
      matrix:
        # platform: [windows-latest]
        # platform: [macos-latest]
        #python-version: [3.9]
        # platform: [macos-latest,windows-latest]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - env:
          KEY: ${{ secrets.KEY }}
        run: |
          ./run.sh
          ./commit.sh && echo ::set-output name=push::1 || true

      - name: push
        if: steps.run.outputs.push == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
